services:
  - type: web
    name: insurance-fraud-detection
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
